### ISSUE TITLE
remove_group does not seem to work

### ISSUE THREAD

**Issue by damianpop** [kronenthaler/mod-pbxproj#53]
`project.remove_group_by_name("Hola")` Does not remove the group "Hola".

And the following code creates the group "Hola" and leaves it present in the project. 
Shouldn't it remove it too?

```
group = project.get_or_create_group("Hola")
project.remove_group(group)
project.save()
```

**Comment by kronenthaler** [comment]
Please, read the method signature. `remove_group` uses an _id_ to remove the group.
`remove_group_by_name` removes the group based on the _name_.

**Comment by damianpop** [comment]
Sorry, doesn't `get_or_create_group` return an id too?

**Comment by kronenthaler** [comment]
It returns a group object, those objects are required by other methods for instance to add_file, you may want to specify that the file goes under a specific group (object)

**Comment by damianpop** [comment]
I see. Then what's the way to remove a group? I don't seem to succeed with `remove_group_by_name` either.
This leaves the project with the group named "Hola":

		group = project.get_or_create_group("Hola")
		project.remove_group(group.id)
		project.remove_group_by_name("Hola")
		project.save()

Thanks

**Comment by huazi2015** [comment]
i also ask this question , please

**Comment by kronenthaler** [comment]
I checked it. It was a bug, and it's fixed already in the master branch. Pull request #57 if you are curious about the changes.

**Comment by damianpop** [comment]
Thanks @kronenthaler . The group is removed now. 
Anyway I have one more question about this:
If the group containse source files, these are not removed from the *Compile Sources* build phase. 
What would be the approach to take regarding this?

**Comment by kronenthaler** [comment]
try with the recursive flag of the method.
remove_group_by_name('name', True)

**Comment by damianpop** [comment]
With the recursive flag it fails with this error:

```
Traceback (most recent call last):
  File "./BuildFromWorkspaceUsingBundles.py", line 108, in <module>
    project.remove_group_by_name(adapterName, True)
  File "/Users/damian.troncoso/Desktop/workspace/LIMA-docs/Tools/AutomatedBuilding/mod_pbxproj/mod_pbxproj/mod_pbxproj.py", line 1002, in remove_group_by_name
    self.remove_group(group.id, recursive)
  File "/Users/damian.troncoso/Desktop/workspace/LIMA-docs/Tools/AutomatedBuilding/mod_pbxproj/mod_pbxproj/mod_pbxproj.py", line 983, in remove_group
    name = self.objects.get(id).get('path')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by kronenthaler** [comment]
I will check it over the weekend

On Fri, May 29, 2015 at 9:36 PM, Damian <notifications@github.com> wrote:

> With the recursive flag it fails with this error:
>
> Traceback (most recent call last):
>   File "./BuildFromWorkspaceUsingBundles.py", line 108, in <module>
>     project.remove_group_by_name(adapterName, True)
>   File "/Users/damian.troncoso/Desktop/workspace/LIMA-docs/Tools/AutomatedBuilding/mod_pbxproj/mod_pbxproj/mod_pbxproj.py", line 1002, in remove_group_by_name
>     self.remove_group(group.id, recursive)
>   File "/Users/damian.troncoso/Desktop/workspace/LIMA-docs/Tools/AutomatedBuilding/mod_pbxproj/mod_pbxproj/mod_pbxproj.py", line 983, in remove_group
>     name = self.objects.get(id).get('path')
> AttributeError: 'NoneType' object has no attribute 'get'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kronenthaler/mod-pbxproj/issues/53#issuecomment-106910964>
> .
>



-- 

.: Kronenthaler :.

kronenthaler@gmail.com | yahoo.com

**Comment by damianpop** [comment]
Thanks a lot!

**Comment by huazi2015** [comment]
i find a issue, this method "get_groups_by_name" also cannot use it, like this：
new_group1 = pbproject.get_groups_by_name('Test_Group')
pbproject.remove_group(new_group1.id)

error： Traceback (most recent call last):
  File "/Users/liangma/QinMoon/Editor_pbxproj/Build_pbxproj.py", line 61, in <module>
    pbproject.remove_group(new_group1.id)
AttributeError: 'list' object has no attribute 'id'
[Finished in 0.3s with exit code 1]

**Comment by kronenthaler** [comment]
I couldn't reproduce your error. Neither with the `remove_group_by_name` or `remove_group`. Here is the script i used to test. 

```
#!/bin/python
from mod_pbxproj import XcodeProject

project = XcodeProject.Load('test/test.xcodeproj/project.pbxproj')
# create Hola/bye/source.m
group = project.get_or_create_group("Hola")
groupB = project.get_or_create_group(name="bye", parent=group)
project.add_file_if_doesnt_exist("source.m", parent=groupB)
# remove recursively using the string name
project.remove_group_by_name("Hola", True)

# create Hola/bye/source.m
group2 = project.get_or_create_group("Hola")
groupB2 = project.get_or_create_group(name="bye", parent=group2)
project.add_file_if_doesnt_exist("source.m", parent=groupB2)
# remove recursively using the group2 instance + id
project.remove_group(group2.id, True)

project.save()
```

**Comment by damianpop** [comment]
I meant whan there's a group within a group, both with the same name.
So for example this:

```
group = project.get_or_create_group("Hola")
groupB = project.get_or_create_group(name="Hola", parent=group)
project.remove_group_by_name("Hola", True)
project.save()
```

**Comment by kronenthaler** [comment]
True, but that operation is ambiguous. 
Both groups have the same name, there is no way to ensure which one was deleted first (the parent or the child).
In such cases use the `id` to resolve the ambiguity yourself.

**Comment by damianpop** [comment]
But if I use the id, the source files are not removed from the Compile Sources build phase.

**Comment by kronenthaler** [comment]
I fixed that issue on pull request #57 give it a try

**Comment by damianpop** [comment]
I just checked it. It's not fixed :/ 
`project.remove_group(group.id)` still leaves the source files in the Compile Sources build phase, which leads to compiler errors.

**Comment by kronenthaler** [comment]
This is the code i have been using to test the feature:

```
#!/bin/python
from mod_pbxproj import XcodeProject

project = XcodeProject.Load('test/test.xcodeproj/project.pbxproj')
# add a file to the sources
group = project.get_or_create_group("Hola")
groupB = project.get_or_create_group(name="Hola", parent=group)
project.add_file_if_doesnt_exist("source.m", parent=groupB)

# comment out to actually remove the file
# project.remove_group(group.id, True) # note the True to make it recursive.

project.save()
```
Create an empty project and run over that project. It will create: Hola/Hola/source.m 
Check that the file is in the sources section of the target.
Un-comment the remove_group and run again.
Check again the sources section of the target. It should be gone.

If this works, the problem is in your script.

**Comment by damianpop** [comment]
Sorry, I didn't realize I could use `remove_group` with the recursive option :)
It's working now. 
Thanks a lot!
